### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Snehithadevarapu** [yudanta/id-ner-spacy-fast-api#1]
Hi, 
I have implemented spacy -fastapi service in my local machine with your code. I have used my custom model and run the main.py . However the reloader process started to load I get the traceback error as mentioned below:

2021-03-16 08:57:16,139 loglevel=INFO   logger=root <module>() L15   loading spacy nlp model
nlp_models/model_spacy
2021-03-16 08:57:16,916 loglevel=INFO   logger=pytorch_transformers.modeling_bert <module>() L226  Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2021-03-16 08:57:16,937 loglevel=INFO   logger=pytorch_transformers.modeling_xlnet <module>() L339  Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2021-03-16 08:57:17,827 loglevel=INFO   logger=root <module>() L19   done loading spacy nlp model
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/opt/conda/lib/python3.6/site-packages/uvicorn/main.py", line 407, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/opt/conda/lib/python3.6/site-packages/uvicorn/main.py", line 414, in serve
    config.load()
  File "/opt/conda/lib/python3.6/site-packages/uvicorn/config.py", line 300, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/conda/lib/python3.6/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app/main.py", line 47, in <module>
    from .routes import nlp
  File "./app/routes/nlp.py", line 15, in <module>
    404: {'description': 'Not Found'}
TypeError: __init__() got an unexpected keyword argument 'prefix'

Can you please help me out .

**Comment by yudanta** [comment]
What version of spacy do you use? 

Mine is:
`spacy==2.3.5`

**Comment by Snehithadevarapu** [comment]
Hi, 

I also use spacy 2.3.5 and python version 3.8.5
